language: java

jdk:
  - openjdk11
  
before_install:
  - chmod +x mvnw
  
cache:
  directories:
  - $HOME/.m2
 
 # Definir o Deploy no Heroku
deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  edge: true 
  app: jwt-scheiner
  on:
      branch: main
      jdk: 
       - openjdk11
